### ISSUE TITLE
Dev mode reloads TS changes twice, leaving the user with an empty screen

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/hilla#1134]
### Description of the bug 
When I make a change to a TS view in React, the update gets displayed correctly. But after a while, the screen refreshes and shows an empty page. 

### Minimal reproducible example
Create a project with `npx @hilla/cli --init react`, change a view

### Expected behavior
It should work.

### Actual behavior
It doesn't. The following gets displayed in the console. I have cleared all service workers etc from the domain. 
<img width="757" alt="Screenshot 2023-08-11 at 09 41 49" src="https://github.com/vaadin/hilla/assets/883698/e24398bc-5439-4fab-accf-0ed69c7e4617">

### Versions:
    - Vaadin / Hilla version: 2.1.4
    - Node version: 19.5
    - Java version: 17
    - OS version: MacOS
    - Browser version (if applicable): Chome latest

**Comment by Artur-** [comment]
I think the issue here is that Vite restarts and the browser refresh happens during the restart. Then you get 500 for all resources. 

The Vite restart issue is fixed in https://github.com/vaadin/flow/pull/17433 

What remains strange here is why you get the restart when changing a TS file because the whole chain of events start from Spring Boot restarting, which happens when changing a file on the classpath, not when changing a TS file
