### ISSUE TITLE
Include the java type in the generated model metadata

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#1271]
To be able to e.g. format better in an autogrid, the model metadata needs to contain the Java type

**Comment by cromoteca** [comment]
Did you think of any preferred format for that metadata?

**Comment by cromoteca** [comment]
Some months ago I made a prototype at https://github.com/cromoteca/jackson-parser that uses a [reviver](https://github.com/cromoteca/hilla/blob/42bf5f1e554b2a341b7f0683ff59f862cc27754f/packages/ts/hilla-frontend/src/Connect.ts#L422-L442) to transform a JSON like

```json
{
    "date": {
        "__hilla_type": "Date",
        "value": "2023-09-14T12:59:44.632+02:00"
    },
    "uuid": "e8aee4dd-f894-47a8-b8da-61f018b4052f",
    "map": {
        "__hilla_type": "Map",
        "entries": [
            {
                "key": 3,
                "value": 4.0
            },
            {
                "key": 0,
                "value": 0.1
            },
            {
                "key": 1,
                "value": 2.0
            }
        ]
    },
    "bigInteger": {
        "__hilla_type": "BigInt",
        "value": "1234567890123456789012345678901234567890"
    },
    "other": {
        "__hilla_type": "Date",
        "value": "2023-09-14T13:16:24.633+02:00"
    }
}
```
to
```javascript
{ 
  date: Date Thu Sep 14 2023 12: 59: 44 GMT +0200(Central European Summer Time),
  uuid: "e8aee4dd-f894-47a8-b8da-61f018b4052f",
  map: Map(3), // now it's a record which loses Map generic types
  bigInteger: 1234567890123456789012345678901234567890n,
  other: Date Thu Sep 14 2023 13: 16: 24 GMT +0200(Central European Summer Time)
}
```
And a replacer to do the same in the opposite direction.

I'm not saying we should change our JSON format now (it would break everything). What I mean is that it would be nice to add type information in a way that can be used when dealing with JSON.

Would it be fine for you to find type information in the data rather than in the model? I guess no.

**Comment by Artur-** [comment]
Sound inefficient to send the types always with the data. As the Java class structure is fixed, so should the type of values be so it should be enough to include it once in the model.
