### ISSUE TITLE
[autogrid] support custom titles for auto created columns

### ISSUE THREAD

**Issue by taefi** [vaadin/hilla#1444]
### Describe your motivation

* Developers should be able to define custom titles for the grid's auto created columns.
* Custom fields/column (combined `firstname + lastname` to show `fullname` instead) should be supported.

**Comment by knoobie** [comment]
@taefi Just a note to consider (so this doesn't interfere / creates problems later on): 

The grid web component is still missing i18n for e.g. accessibility, see: https://github.com/vaadin/web-components/issues/3471

So shameless idea (because I want it there 😬): would it make sense to start in the web component and extend from that i18n property to define additional values for the auto grid?

**Comment by tarekoraby** [comment]
Thanks for the suggestion @knoobie. For now, we will prioritize enabling custom titles, postponing the handling of i18n to some later point. When we tackle i18n, we will consider addressing those issues in the web component as you suggested.

**Comment by taefi** [comment]
This issue was broken down to smaller issues: #1568 and #1569

**Comment by taefi** [comment]
Closed by #1522
