### ISSUE TITLE
Incorrect generated enum values in TS model

### ISSUE THREAD

**Issue by KardonskyRoman** [vaadin/hilla#1517]
### Describe the bug

The java enum is:
```java
public enum TYesNo {

    ДА("\u0434\u0430"),

    НЕТ("\u043d\u0435\u0442");

    private final String value;

}
```

This is generated TS class:
```ts
enum TYesNo {
    ДА = "\u0414\u0410",
    НЕТ = "\u041D\u0415\u0422"
}
export default TYesNo;
```

As you can see, unicode values are different. 

### Expected-behavior

Unicode values from java and TS  should match 

### Reproduction

above

### System Info

Hilla 2.2.2

**Comment by Lodin** [comment]
This is an expected behavior. Currently, the generator accepts only the name of the enum variant but not its value. The reason is that the value type in Java can be anything while the TypeScript enum supports only strings and numbers.

For your case, since the difference is only in the letter case, I would suggest to use `TYesNo.ДА.toLowerCase()`. Another possible workaround is to use a map with correct values along with the enum or instead of it.
