### ISSUE TITLE
With Hilla/Lit in the latest version (2.3.1) Binder.interpolateMessageCallback is not being called. 

### ISSUE THREAD

**Issue by TatuLund** [vaadin/hilla#1618]
### Describe the bug

With Hilla/Lit in the latest version (2.3.1) Binder.interpolateMessageCallback is not being called. 

### Expected-behavior

Binder.interpolateMessageCallback is called.

### Reproduction

For testing, compare my Hilla 1.3 version of the app here
https://github.com/TatuLund/hilla-demo/blob/master/frontend/index.ts#L20
vs. Hilla 2.3 version in Johannes fork, where it is not called
https://github.com/JohannesT/hilla-demo/blob/master/frontend/index.ts#L20

### System Info

Browser and OS independent.

**Comment by Lodin** [comment]
The problem here is that we splitted a single `Binder` class to `Binder` and `BinderRoot`, and the `interpolateMessageCallback` is not belongs to `BinderRoot`. 

The workaround here is to replace the call to `Binder` with the call to `BinderRoot`:
```ts
import { BinderRoot } from '@hilla/form';
  // ...
BinderRoot.interpolateMessageCallback = (message, validator, binderNode) => {
  // ...
};
```

I'm going to prepare a fix that would allow to use both classes.
