### ISSUE TITLE
[autocrud] Number fields in forms show 0 by default

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/hilla#1827]
### Describe the bug

The number fields of the AutoCrud form have the value of 0 when no item is selected.

![image](https://github.com/vaadin/hilla/assets/42799254/2a01e93e-54b1-46d2-ade5-1cb1d8f0f03a)

### Expected-behavior

The fields are blank when no value is selected.

### Reproduction

Create an AutoCrud based on a NumberModel.

### System Info

Irrelevant

**Comment by sissbruecker** [comment]
The issue is caused by how the Hilla Binder / Form works. It creates an empty value initially, and when clearing the form, and initializes all non-nullable properties with a default empty value. For example `0` for numbers, or the first enum value for an enum property.

I have explored some workarounds but have not managed to find one that doesn't introduce new issues. With that I can only think of some more complex options:
- A new feature could be added to the Binder where you can tell it that you are not really editing something at the moment. That would still configure the fields properly, such as showing required indicators but would not bind, or rather clear, any field values. From a practical perspective this feature would only be useful when the form is in a disabled state, so maybe it should be called something like `disabled`, and the fields should be disabled automatically by enabling this.
- Change the Binder behavior to only set the `value` on the field element if it's not the default value. Ideally this should only happen when Binder creates a default value on its own. If a developer reads a value into the Binder that says a properties' value is `0` then `0` should still show up.
- Change the `AutoCrud` UX so that the form only shows after selecting an item or creating a new one. That would require some additional considerations such as figuring out if there should be a cancel button, how to make `AutoForm` show a cancel button only when used in an `AutoCrud` and if there should be some other indicator in `AutoCrud` that items in the grid are editable.
