### ISSUE TITLE
[i18n] Language detection

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/hilla#2102]
The I18n system should automatically detect a sensible language for which to load the initial translations. It could work like this:
- When a user opens the app for the first time, use the browser language (`navigator.language`)
- If a user has changed the language before in a previous usage of their app, use that

To allow for app-specific logic, developers should be able to specify an explicit language when initializing I18n, which overrides auto-detection. One use-case could be that a user's preferred language is stored in their user profile. The app could load that profile and initialize I18n with the language of that profile.

Language detection is planned to run on the client for now. The last used language can be stored in locale storage.

**Comment by Legioth** [comment]
> The last used language can be stored in locale storage
Would it make sense to have it in a cookie instead so that the server could e.g. eagerly include the right translations when generating `index.html`? The cookie value could additionally contain a hash of the previously loaded translation so that the server could avoid including it if the client is already expected to have the latest version cached.

**Comment by sissbruecker** [comment]
Thanks, that makes sense I guess. If we don't want to implement any eager loading yet we could still let the server update the hash in the cookie value to let the client know whether the cached translations are out of date and should be updated.
