### ISSUE TITLE
[Full-stack Signals] allow client-side signal's default value to be set upon creation

### ISSUE THREAD

**Issue by taefi** [vaadin/hilla#2625]
### Describe your motivation

As prerequisite for offline-support, it is necessary for the client-side instance of a shared signal to have a default value when created, without having to wait for a round-trip to the server (to bring the actual default / latest value).

### Describe the solution you'd like

It is suggested to have an API such as an extra object argument with the `{defaultValue: T}` key for signal methods that allows the default value to be set:

```ts
const counter = CounterService.counter({defaultValue: 1});
const name = NameService.name({defaultValue: ''});
const approved = LicenseService.approved({defaultValue: false});
```

The `defaultValue` is required for non-nullable value signal endpoints. Nullable signal methods accept `{defaultValue: undefined}` value.

**Comment by Legioth** [comment]
I suspect it would be confusing to have different default initial values for different `T` types in `ValueSignal<T>` since that type information only exists in TS but not in the transpiled JS. There's nothing that prevents us from embedding the information when we generate the TS code but it might still be confusing to the developer. It would also open up a can of worms with regards to whether the default for e.g. `ValueSignal<string>` should be `undefined` or an empty string.

A related note is that the inability of knowing the initial value means that the type of `NameService.name()` would have to be `ValueSignal<string | undefined>` whereas the type of `NameService.name().withDefaultValue("")` would be `ValueSignal<string>`. This does on the other hand lead to the potentially unwanted side effect that it would be valid to do `someValueSignal.value = undefined` unless we do some crazy things with the TS types.

**Comment by taefi** [comment]
In this case, do you see any caveats in implementing #2623 in a way that keeps `ValueSignal<T>` abstract as it is and introduces `StringSignal` and `BooleanSignal`? Then, for implementing this API, each concrete type would implement its own typed version of the `withDefaultValue` to remove the confusion for developers.

Deciding on the default value of `StringSignal` to be either `undefined` or an _"empty string"_ is a hard thing ;) Personally, I'm found of the idea of a more limited version for implementation without supporting `undefined` at all for the so called _`"StringSignal"`_.

**Comment by Legioth** [comment]
What value would a dedicated `StringSignal` or `BooleanSignal` type have other than using a different default value?

I was also thinking that we could provide an annotation for defining the default value on a method with the gotcha that this value would always be a (JSON) `String` due to the way annotations work. In that way, the default could be embedded in the generated TS and thus be immediately available on the client.

```java
@DefaultValue("false")
public ValueSignal<Boolean> approved() {
  return approved;
}
```

**Comment by Legioth** [comment]
> keeps `ValueSignal<T>` abstract as it is and introduces `StringSignal` and `BooleanSignal`?

What about `ValueSignal<LocalDate>`, `ValueSignal<MyBean>` or any other type that you might want to send as a readonly JSON object?

**Comment by taefi** [comment]
To make sure I'm understanding _what are we trying to solve here_, I need to understand "what" and "why" having something like the following could be confusing for the developers:

When implementing #2623, we can expose `ValueSignal<T>` as a non-abstract class to hold any generic values (that we can support in Hilla), so an instance of `ValueSignal<T>` would only accept type default values of type `T` as args. In this way the instances are obtained from the service are typed like this (the followings would be generated in the future): 
```ts
export class ValueSignalServiceWrapper {
  static someBooleanValue() {
    const signalChannel =
      new ValueSignalChannel<boolean>('ValueSignalService.someBoolean', client_1);
    return signalChannel.signal;
  }

  static someStringValue() {
    const signalChannel =
      new ValueSignalChannel<string>('ValueSignalService.someString', client_1);
    return signalChannel.signal;
  }

  static someDateValue() {
      const signalChannel =
      new ValueSignalChannel<Date>('ValueSignalService.someDate', client_1);
      return signalChannel.signal;
  }
}
```
Then, both the compiler and the IDE are accepting/suggesting the correct type on each instance:
![Screenshot 2024-07-30 at 13 37 48](https://github.com/user-attachments/assets/7b880e76-769d-4d3c-b54e-c9899d196db0)

![Screenshot 2024-07-30 at 13 38 12](https://github.com/user-attachments/assets/1de7f511-3e8c-4e5c-8769-a2d95717b938)

![Screenshot 2024-07-30 at 13 39 05](https://github.com/user-attachments/assets/db7acf26-e365-4245-93a0-569e52540e39)

**Comment by Legioth** [comment]
What's the type before the `withDefaultValue()` step, i.e. the type of `x` in this example:
```
const x = ValueSignalServiceWrapper.someBooleanValue();
```

I would recommend typing out the return type in the generated code rather than letting it be inferred. This helps make the code slightly more readable and makes it slightly easier to detect any unexpected bugs in the code generation.

**Comment by taefi** [comment]
The type inference with `ValueSignal<T>` seems to be working fine:
![Screenshot 2024-07-31 at 10 44 50](https://github.com/user-attachments/assets/02de231d-45c0-4572-ad39-f2fb1955a50d)
And strictly typing them is also fine:
![Screenshot 2024-07-31 at 10 47 36](https://github.com/user-attachments/assets/112954df-0ca5-4967-9869-848081992928)
So nothing prevents us from adding the types in the generated service codes as well, though, the above is also fine IMO.

**Comment by Legioth** [comment]
Should it be `ValueSignal<boolean>` or `ValueSignal<boolean | undefined>` before `withDefaultValue`? `booleanValue.value` will be `undefined` before the initial value has been fetched from the server which means that users might observe a value that isn't compatible with the declared type if that's `ValueSignal<boolean>`.

**Comment by Legioth** [comment]
My suggestion about typing out the types was for the method signature in the generated code, e.g.
```
static someBooleanValue(): ValueSignal<boolean | undefined> {
```

**Comment by taefi** [comment]
>  booleanValue.value will be undefined before the initial value has been fetched from the server ...

This is missing from the typing at the moment. The ValueSignal<T> should be able to support having that `undefined` state, and the NumberSignal should inherit it (or change to support this).

**Comment by Legioth** [comment]
`NumberSignal` has `0` as the default value so there's no need for `undefined` there.

**Comment by Legioth** [comment]
As discussed separately, the use of an instance method messes up type signatures especially in combination with nullability since there are cases where the setter and the getter would have different types.

Instead, we should provide a way of defining the default value through an options object when creating an instance, i.e. `NameService.name({defaultValue: ""});`

**Comment by platosha** [comment]
With endpoint arguments:

```tsx
const signal: ValueSignal<string> = SomeService.someSignal(someArgument, {defaultValue: "foo"});
```
