### ISSUE TITLE
[Full-stack Signals] Nonnull value signal type parameter causes TS error in generated code

### ISSUE THREAD

**Issue by Legioth** [vaadin/hilla#2719]
### Describe the bug

An endpoint method returning a `ValueSignal<String>` in a package with `@NonNullApi` leads to invalid generated TypeScript. I assume the same would happen with a `ValueSignal<@Nonnull String>` in a package without `@NonNullApi`.

The error I get is like this:
```
[TypeScript] Type 'ValueSignal<undefined>' is not assignable to type 'ValueSignal<string>'. Type 'undefined' is not assignable to type 'string'.
/Users/lastrand/git/poll/src/main/frontend/generated/StatsService.ts:14:5
    12 | }
    13 | function foo_1(): ValueSignal_1<string> {
  > 14 |     return new ValueSignal_1(undefined, { client: client_1, endpoint: "StatsService", method: "foo" });
       |     ^^^^^^
    15 | }
```

### Expected-behavior

Either the case should be fully supported or alternatively, there should either be an error message explicitly saying that value type must be nullable.

### Reproduction

Include a class like this and run.
```
@BrowserCallable
@Service
public class StatsService {
      private final ValueSignal<String> foo = new ValueSignal<>(String.class);
      public ValueSignal<@Nonnull String> foo() {
        return foo;
    }
}
```

### System Info

Vaadin 24.5.0.alpha16

**Comment by taefi** [comment]
In `24.5.0.alpha16`, the generated return types are reflecting what is defined on the java side correctly. The source of the problem is that the client-side default value of a `ValueSignal<T>` is always generated as `undefined`.

The correct way to address this is to keep the generated returned type as is and to address #2625.

In the meantime, the workaround is either the users to always annotate the value type for a ValueSignal with `com.vaadin.hilla.Nullable` e.g. 
```java
public ValueSignal<@Nullable String> someSignal() { ... }
```
Or, we may change the generator to always generate `ValueSignal<T | undefined>` as the return type.
