### ISSUE TITLE
Layout.tsx Not Working After Upgrade to Vaadin 24.6.0

### ISSUE THREAD

**Issue by Jusius** [vaadin/hilla#3085]
### Describe the bug

After upgrading from Vaadin 24.5.x to 24.6.0, the main layout stops working for all routes except the root path (`/`). When navigating to any other route, the layout disappears completely.

Environment
- Vaadin version: 24.6.0
- Previous working version: 24.5.x
- Using Vaadin Flow with React components
- Using Hilla file router (`@vaadin/hilla-file-router`)

Working Behavior (24.5.x)
- Layout appears consistently across all routes
- Navigation works correctly with layout maintained
- SideNav and other layout components remain visible during navigation

Current Behavior (24.6.0)
- Layout only appears on root path (`/`)
- When navigating to other routes (e.g., `/sales-orders`, `/accounting`), the layout disappears
- Only the route content is shown without the surrounding layout

### Expected-behavior

Layout should persist across all routes as it did in version 24.5.x, maintaining the consistent structure of the application regardless of the current route.

Is there any change in 24.6.0 regarding how layouts should be configured with Flow when using React components? The fact that it works on the root path but not other routes suggests a potential change in the routing/layout system.

### Reproduction

1. Create a project using Vaadin 24.5.x with the above layout configuration
2. Verify layout works correctly across all routes
3. Upgrade to Vaadin 24.6.0
4. Navigate to any route other than root (`/`)
5. Observe layout disappears

### System Info

Win 10 64bit , using hilla with flow hybrid

**Comment by taefi** [comment]
@Jusius thanks for upgrading and creating this issue. Would it be possible to show what's the exact setup you have problem with, since I couldn't exactly get what "Create a project using Vaadin 24.5.x with the above layout configuration" means, when it comes to the details :)

The reason I'm asking for a minimal project that shows the problem is that the FS-based routing is heavily based on convention-over-configuration, e.g. suggesting a file containing the layout should be named as `@layout.tsx` to be picked up by the FS Router. Now, in 24.6, Flow support for automatic Java layouts is added, so it means there's a chance that something in you project may not be as the framework expects.

**Comment by Jusius** [comment]
hi @taefi , thanks for the response 

for now my setup is like this : 
1. i create a blank main layout that extends to applayout with flow 
2. create a views with flow and @Route annotion but not adding the Layout = MainLayout.class
3. create a path on layout.tsx to go to the link 

e.g : 

{(hasRole('USER') || hasRole('ADMIN')) && (
            <SideNavItem path="/master-data" onClick={() => {
  }}>
  <Icon icon="vaadin:archive" slot="prefix" />
  Master Data
</SideNavItem>
            )}
            
on vaadin 24.5.x all of these is works normally

**Comment by Jusius** [comment]
i found the solution 

it seems on vaadin 24.6.0 , the index.tsx is really necessary to link the layout.tsx and the Flow @Route annotion 

not it works perfectly with my current setup ( all of the navigate , layout , etc are on the layout.tsx )
