### ISSUE TITLE
`BigDecimal` is not supported in multi-module generator

### ISSUE THREAD

**Issue by cromoteca** [vaadin/hilla#474]
When running integration tests with the multi-module generator, this code:

```java
public BigDecimal getBalance() {
    return bankService.getBalance();
}

```
is translated to
```typescript
function getBalance_1(init?: EndpointRequestInit_1): Promise<unknown> {
    return client_1.call("BalanceEndpoint", "getBalance", {}, init);
}
```

`BigDecimal` was mapped to `number` in the old generator.

**Comment by Legioth** [comment]
I'm quite sure `number` isn't the right representation for `BigDecimal` since the reason for using `BigDecimal` rather than e.g. `Double` on the Java side is that you'd want to have more precision than what's offered by 64-bit floating point. Since JS doesn't (yet) have arbitrary-precision decimal numbers, the most accurate representation would most likely be as a string. The main reason for doing that as a regular JS number would thus be to maintain backwards.
