### ISSUE TITLE
Parser considers too many dependencies as “entities”

### ISSUE THREAD

**Issue by platosha** [vaadin/hilla#488]
When trying to use the multi-module engine in the hilla-crm-tutorial application, the parser fails with an error after attempting to parse a class from `reactor.core.publisher.Flux`. Debugging revealed the following:

- `ScanElementsCollector` iterates the initially discovered endpoints and entities, and calls `getDependenciesStream()` to iterate the dependencies and discover more entities.
- `getDependenciesStream()` combines all kinds of dependencies, including interfaces, superclass, fields, methods, inner classes and type parameter ones.
- For `CrmEndpoint`, the following entities are erroneously found: `CompanyRepository`, `ContactRepository`, `StatusRepository`, although they don’t participate in actual endpoint parameter and return types.
- Furthermore, when parsing those repository entity classes, it scans `JpaRepository` dependencies, and this eventually fails with a weird message when trying to resolve type arguments for `reactor.core.publisher.Flux`...

I would suggest following these additional rules in `ScanElementsCollector` to prevent going through unnecessary entities:

1. For endpoint classes, only consider endpoint method dependencies as entities. Skip constructor and field dependencies that do not participate in actual endpoint method parameter / return types.
2. For entity classes, only consider field dependencies. The method dependencies and therefore interfaces of entities could be skipped.

**Comment by cromoteca** [comment]
Duplicate of #487

**Comment by cromoteca** [comment]
I'd not limit to field dependencies: actually, since we're essentially talking about data transmission between client and server, implementation details should not matter for us. For example, if (just as a dumb example) a private `int` field is exposed as `BigInteger` through a `getter/setter` pair, we should care about `BigInteger`, not `int`.

I propose to limit us to what is `public`. That looks like a reasonable contract to me: only transfer what is public. We should definitely skip everything that is `private`, like the `BankService` in the [BalanceEndpoint](https://github.com/vaadin/hilla/blob/main/packages/java/tests/spring/security/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java) I cited in #487.

There might edge cases where `protected` or default visibility scopes might come into play. I find it weird to need to transfer those kind of fields, as that probably indicates poorly-designed APIs.

**Comment by cromoteca** [comment]
Actually it depends on how the controller serializes things: does it serialize fields or Java Bean properties? I'll have a look at the code, but you probably already know the answer.

**Comment by platosha** [comment]
AFAIK the old generator uses fields as the reference, so that’s why I’d suggest that. Also we need to stay aligned with the runtime controller that uses Jackson.

**Comment by platosha** [comment]
Anyway, let’s continue this discussion in #487, as this is a duplicate issue.
