### ISSUE TITLE
Production mode build appears to be broken in 1.2 beta2

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/hilla#528]
I did a production build with `mvn package -Pproduction` and it led to the following network graph with this project: [hilla-react-crm](https://github.com/marcushellberg/hilla-react-crm)

<img width="1022" alt="Screen Shot 2022-08-21 at 12 41 34" src="https://user-images.githubusercontent.com/883698/186010635-01f0a867-759f-46ed-9644-a64f21182095.png">

The current version of start.vaadin.com shows a similar graph. 

I wasn't able to reproduce the issue with a minimal project, but needs to be investigated.

**Comment by Artur-** [comment]
>The current version of start.vaadin.com shows a similar graph.

This was fixed by taking `splitVendorChunkPlugin()` from Vite into use. Without it there is no chunking strategy so everything is put in individual files. `splitVendorChunkPlugin` uses the strategy that was in Vite 2.8 and earlier which is to create one chunk consisting of the entry point(s) and their imports.
