### ISSUE TITLE
Multi-module: ERROR (tsgen) <ModelPlugin>: Component is not an object: enum

### ISSUE THREAD

**Issue by svein-loken** [vaadin/hilla#542]
### Description of the bug

Cannot generate enum

### Expected behavior

-

### Minimal reproducible example

-

### Versions

Hilla: 23.2.0.rc1
Flow: 23.2.0.rc2
Java: JetBrains s.r.o. 17.0.2
OS: amd64 Windows 10 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Live reload: Java active (HotswapAgent): Front end active

**Comment by svein-loken** [comment]
![image](https://user-images.githubusercontent.com/105504445/188393225-a283a980-8a1c-4ee4-afd4-6bd7890b3ba0.png)

**Comment by Lodin** [comment]
Minimal reproducible example:
- Run `npx @vaadin/cli init --hilla --auth hilla-with-auth`
- Add `com.vaadin.experimental.hillaEngine=true` to `src/main/resources/vaadin-featureflags.properties`
- Run `npm install`
- Run `mvn spring-boot:run`

You will get the described failure for the `RoleModel` file (model representation of `src/main/java/com/example/application/data/Role.java`).

What happens:
Model plugin cannot consume enums, so it just generates nothing. However, TS wants to import the result of generation which leads to application failure.

**Comment by Lodin** [comment]
The old generator just produces an empty class for enum. I wonder how it should look for the Hilla Engine.

### Proposal

Since enum cannot have model at all, we could  just analyze the link to the enum, understand that it is an enum and import the original file created by `BackbonePlugin`. So instead of `RoleModel` we will just have a `Role` enum import here.
