### ISSUE TITLE
Form-Binder: Unable to test nullable field for empty

### ISSUE THREAD

**Issue by Feuerwerk** [vaadin/hilla#560]
### Description of the bug 
Having a form with a custom validator, the validator of a nullable property is **not** called when the field is empty

### Minimal reproducible example

[my-hilla-app.zip](https://github.com/vaadin/hilla/files/9644668/my-hilla-app.zip)

This example will show you the bug. When you leave the field empty the validator should fail and show a red notification

### Expected behavior

The custom validator should be called even if the field is empty

### Actual behavior

The custom validator is not called if the field is empty

### Possible workaround

The error only occurs if you add the validator directly to the field e.g.
`
this.binder.for(model.name).addValidator({
	message: 'Must not be empty',
	validate: (value) => {
		return (value ?? '').length > 0;
	},
});
`

If you add a global validator instead you're still able to catch the empty field e.g.
`
this.binder.addValidator({
	message: 'Must not be empty',
	validate: (document) => {
		return (document.name ?? '').length > 0;
	},
});
`

### Versions:
    - Vaadin / Hilla version: 1.2.1
    - Java version: 17.0.2

**Comment by Lodin** [comment]
Hi @Feuerwerk! Thanks for your contribution.

I took a look at your code and found that it could be fixed in the following way: 
```ts
protected firstUpdated(_changedProperties: PropertyValues): void {
  super.firstUpdated(_changedProperties);

  const model = this.binder.model;
  this.binder.for(model.name).addValidator({
    message: 'Must not be empty',
    validate: (value) => {
      return (value ?? '').length > 0;
    },
    // Adding this option will make the field required by default
    impliesRequired: true,
  });
}
```
The algorithm here is the following:

- If the field is not required, no validators will be run if the field is empty, even if the custom validator is set.
- The Binder marks any field required if it has the standard validator (e.g., `@NotNull` at the Java side) set.
- To make custom validator behave as the standard validator, you have to set `impliesRequired` option when adding the validator. It will make the field required.

**P.S.** Also, to make your code work, you have to remove the `this.binder.read({});` line because it breaks the Binder.
