### ISSUE TITLE
Remove the source based generator

### ISSUE THREAD

**Issue by platosha** [vaadin/hilla#734]
After #733, there is not much value in keeping the source based generator. Let us remove it.

**Comment by Legioth** [comment]
What about the value of giving existing users a way of handling other parts of the upgrade with the old generator first, and then switching to the new one once any other issues have been fully resolved?

**Comment by cromoteca** [comment]
The new generator should be able to emulate the old one by providing a Jackson `ObjectMapper` properly configured: after all, the main difference here is where the TypeScript fields come from.

**Comment by Legioth** [comment]
> The new generator should be able to emulate the old

Even for edge cases like how Kotlin annotations are discovered or things like the [suggestion to](https://github.com/vaadin/hilla/issues/703) change how `Page` is serialized?

**Comment by cromoteca** [comment]
The old generator doesn't support Kotlin at all, so that should not be a concern. Regarding `Page`, if we agree to fully support Jackson, including its converters (see #719), then we can add a converter to the compatible `ObjectMapper` to support the old, limited, Hilla `Page` object, while letting the new default just use the Spring `Page` interface directly.

**Comment by cromoteca** [comment]
Let's not forget to update the GitHub validation action: https://github.com/vaadin/hilla/blob/45fc2b0122811faf4c5a74267717111660243b45/.github/workflows/validation.yml#L166-L167

**Comment by cromoteca** [comment]
Done as part of https://github.com/vaadin/hilla/pull/799
