### ISSUE TITLE
List<@Nonnull String> should always map to Array<string>

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#806]
### Description of the bug 
Given
```
public class HelloWorldEndpoint {

    public static class Obj {
        @Nonnull List<@Nonnull String> hellos;

        public List<String> getHellos() {
            return hellos;
        }

        public void setHellos(List<String> hellos) {
            this.hellos = hellos;
        }
    }

    public @Nonnull Obj sayHello(@Nonnull List<@Nonnull String> something) {
        Obj o = new Obj();
        o.setHellos(List.of("Hello stranger"));
        return o;
    }
}
```

You get
```ts
async function sayHello_1(something: Array<string>, init?: EndpointRequestInit_1): Promise<Obj_1> { return client_1.call("HelloWorldEndpoint", "sayHello", { something }, init); }
```

as expected but you also get

```
interface Obj {
    hellos: Array<string | undefined>;
}
```
which is incorrect.

### Expected behavior
```ts
interface Obj {
    hellos: Array<string>;
}
```

### Versions:
    - Vaadin / Hilla version: 2 rc2

**Comment by cromoteca** [comment]
The problem here is that the getter is nullable. While usually accessors are just a wrapper around a field, there is no guarantee that a getter returns the field as it is and so the (non-)nullability is not necessarily transitive.

But, since annotations are often put on fields, and they definitely are in a Hilla 1.x application, we should make sure that those coming from a field with the same name of the property are taken into account.

**Comment by Artur-** [comment]
But `hellos` is considered nonnull and the getter has no annotation for that?

**Comment by Artur-** [comment]
Start uses Lombok so there is no getter there to annotate though

**Comment by cromoteca** [comment]
AFAIK Lombok should replicate the annotations, although I used it long time ago so I'm not 100% sure.

**Comment by Artur-** [comment]
Adding `@Nonnull` to the getter does resolve the problem but as `@Nonnull` for the `hellos` property is read from the field, it feels quite inconsistent
