### ISSUE TITLE
Improve the Hotswap / JRebel Sync for Endpoints and Typescript generation

### ISSUE THREAD

**Issue by gitgmihd** [vaadin/hilla#863]
**Is your feature request related to a problem? Please describe.**

Our application takes 5-10 minutes to start, we want to add new / change endpoints and use them in the frontend without having to restart the backend. Currently one would have to restart the application to achieve this, new endpoint methods wouldn't be available as they are registered on startup.

**Describe the solution you'd like**

Using a hotswap solution like the Hotswap Agent or JRebel we want to have a possiblity to access the new endpoints and be able to regenerate the typescript hilla sources.
The Hilla devmode Gizmo or a general Hilla-Framework-Endpoint could be a place to add a trigger for the regeneration, sync of the endpoint registry.

We discussed this approach with @TatuLund .

**Describe alternatives you've considered**

We could run mvn hilla:generate to regenerate the typescript sources, but our hilla module is a child module in a big structure and there are issues on running it just for the module. Even if that would work, it would still potentially take up to 20 minutes. For the re-registration of the endpoints we can't think of any alternative than to try to adapt core parts of the hilla framework (the dev.hilla.EndpointRegistry)

**Comment by Artur-** [comment]
For HotswapAgent, it should probably be done in a plugin that triggers the Hilla generator, like https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-vaadin-plugin/src/main/java/org/hotswap/agent/plugin/vaadin/VaadinPlugin.java

**Comment by gitgmihd** [comment]
We already implemented our custom Hilla HotswapAgent Plugin, if you are interested we could share this with you (or Tatu via the expert chat). We would be interested in a more generic solution that would also work for JRebel and can be triggered manually to avoid some unnecessary in-between regeneration of sources.

**Comment by tarekoraby** [comment]
@gitgmihd , to clarify your request, you are asking for a way to regenerate all the auto-generated frontend stuff (not just the ones related to the changes in a specific endpoint). The problem for you is that this doesn't work without restarting the app (which takes 5-10 minutes). If you change something in an endpoint (say, add a new method), JRebel does its magic alright by reloading the updated endpoint into the JVM. The problem is that if you then run `hilla:generate` at this point, the updated endpoint is not considered in the generation of frontend stuff.

Is that description accurate? If so, then it sounds like what you are asking for is to re-register the updated endpoint (or rescan all endpoints if that's how it works) and regenerate the autogenerated frontend stuff accordingly. And trigger all that process from a button.

**Comment by gitgdako** [comment]
Please take into consideration that with using hotswap we have the Vaadin plugin disabled (hotswap-agent.propertis -> disabledPlugins)

**Comment by gitgdako** [comment]
Can you be more specific on the solution? Does it work with IntelliJ/Hotswap/JRebel or are any of these necessary? Is it/will it be ported to 1.x? Can you manually trigger it and/or does it reload automatically?

**Comment by taefi** [comment]
> Can you be more specific on the solution? Does it work with IntelliJ/Hotswap/JRebel or are any of these necessary? Is it/will it be ported to 1.x? Can you manually trigger it and/or does it reload automatically?

@gitgdako The detailed description of how to enable this feature is [here](https://github.com/vaadin/hilla/pull/1146).
But, the answer to your questions:

* If you enable either HotSwapAgent or JRebel in your Dev env, this feature will automatically enabled, unless you disable it (by setting the `hilla.endpoint.hot-reload.enabled=false` in your application.properties file).
* The approach is to poll for the changes of endpoint related classes every 5 sec, and it will regenerate only if it detects a change. The interval is configurable via setting `hilla.endpoint.hot-reload.pollInterval` in application properties file.
* The feature is IDE agnostic, however, I personally tested with IntelliJ and it working fine. When you change a java class and trigger the compilation using the menu or by issuing `Ctrl + Shift + F9` (or `Cmd + Shift + F9` on macOS), IntelliJ is showing a small dialog prompting to whether should it redefine the classes or not every time, so this feature would work much smoother if you enable the class redefinition without that prompt. If you don't see that dialog after compiling a java file, it means that you already have it enabled. 
* The regenerations are happening automatically. No need to do anything manually.

**Comment by tarekoraby** [comment]
@gitgdako, the solution made in #1146 depends on the new endpoint generator that was only made stable in Hilla 2.x. However,  a more-or-less similar generator is available as experimental in 1.3x under a feature flag, namely, the [`hillaEngine` feature flag](https://github.com/vaadin/docs/blob/23d689be2c5cc188d60e2d3e8515ec3c85130382/articles/lit/reference/configuration.adoc#java-compiler-options).

Do you have this feature flag enabled in your project? If so, we can investigate backporting the fix in #1146 to work with the `hillaEngine` feature flag enabled.

**Comment by gitgchpd** [comment]
@tarekoraby , i'm answering for my colleague @gitgdako : i investigaed the solution. for ... reasons ... we are stuck on spring-boot 2.x for some time and therefore hilla 1.3 for now. 

i tried to activate the hilla-engine flag but that doesn't really seem to work for multi-module maven projects because as i see it in 1.3 hilla just runs a Maven Command (dev.hilla.internal.TaskGenerateHillaImpl#prepareCommand) of course not considering multi-module projects and with no possibility to configure what is executed there (and even if there would be a possibility to configure it ... running maven from a running server is an especially bad idea it seems to me)

so if backporting the way this TaskGenerateHillaImpl works in hilla 2.x (via https://github.com/vaadin/hilla/blob/main/packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/core/Parser.java as far as i can tell) is not possible, we have no use for this feature in 1.3.

**Comment by tarekoraby** [comment]
> i tried to activate the hilla-engine flag but that doesn't really seem to work for multi-module maven projects 

I'm not sure I understand because a key point of the [hillaEngine feature flag](https://github.com/vaadin/docs/blob/23d689be2c5cc188d60e2d3e8515ec3c85130382/articles/lit/reference/configuration.adoc#java-compiler-options) is to enable multi-module maven projects. Can you elaborate on the steps you took to enable it? Is it possible that it's enabled already (I suspect so since you're saying that your is a multi-module project already).

Perhaps @TatuLund and his team can help investigate the issue in a screen-sharing session?

**Comment by gitgdako** [comment]
> Perhaps @TatuLund and his team can help investigate the issue in a screen-sharing session?

We have shared a private GitHub Repository with @TatuLund, that reproduces the issue. 
.\frontend\generated\vaadin-featureflags.ts shows the flag as false, therefore we assume it is not activated

**Comment by tarekoraby** [comment]
@TatuLund, please check if enabling the feature flag for this project is possible.

**Comment by gitgdako** [comment]
See also #1102

**Comment by TatuLund** [comment]
@gitgdako I committed the change in feature flags in your example project.
