### ISSUE TITLE
React components, imports optimisations 

### ISSUE THREAD

**Issue by ahsinsiddique** [vaadin/hilla#981]
**Imports of same kind of react component should be in one import statement**
**Current**
import { Accordion } from "@hilla/react-components/Accordion.js";
import { AccordionPanel } from "@hilla/react-components/AccordionPanel.js";
**Expected**
import { Accordion, AccordionPanel } from "@hilla/react-components/Accordion.js";

**Same goes for Tab React component**
**Current**
import { Tab } from "@hilla/react-components/Tab.js";
import { Tabs } from "@hilla/react-components/Tabs.js";
**Expected**
import { Tabs, Tab } from "@hilla/react-components/Tab.js";

**Comment by platosha** [comment]
Thanks for the idea. Let me close as a “won't fix” for now.

We attempted to support some limited cases in past with `GridColumn` and `Grid` exported from the same `Grid.js`, however it turned out suggesting both `GridColumn.js` and `Grid.js` in the IDE, which was confusing.

Dropping support for separate imports also would be a breaking change, so it's unlikely to happen any time soon.
