### ISSUE TITLE
Expose all Vaadin plugin Maven goals

### ISSUE THREAD

**Issue by cromoteca** [vaadin/hilla#988]
Now that we create the Hilla Maven Plugin in our repo, only the Vaadin Plugin goals that are explicitly extended are availabe.

Let's support all the Vaadin goals, not only the most important ones.

**Comment by taefi** [comment]
At the moment, there are five goals in Vaadin plugin:

- prepare-frontend
- build-frontend
- clean-frontend
- convert-polymer
- dance

and `vaadinPrepareFrontend` and `vaadinBuildFrontend` are already adopted in the **hilla-maven-plugin**. 

Since, `vaadinConvertPolymer` does not seem to be relevant for Hilla projects explicitly, it is not a candidate to be exposed under **hilla-maven-plugin** IMO.

Then, the `dance` and `clean-frontend` tasks are also up for debate IMO, as they delete `package-lock.json` and also clearing out the content of `package.json` while these two files are not disposable similar to a Vaadin project. Even though, not having them in v24.1 in comparison to v24.0 looks like a breaking change in a minor release, I couldn't convince myself that the have an actual use for Hilla users. We might consider implementing goals with similar names, but a functionality more relevant to Hilla projects. However, technically, it would be a behavioral breaking change anyway.

**Comment by cromoteca** [comment]
Couldn't agree more. But I don't think that it's a good idea to introduce breaking changes on this, so I propose to expose those goald, but when overriding the `execute()` we could add a log warning to explain what are the consequences of running that goal in Hilla.

**Comment by taefi** [comment]
A log warning is not preventing the disaster anyway :) 
But, they where available for a while now, and users have already adapted to the fact that they are not for use with Hilla.
If we want to keep our releases based on the semantic versioning practices, deprecation and a warning log is the best we can offer until v3.0.
